[*]
wallpaper_mode=crop
wallpaper=/home/thecabbage/Desktop/dexterslab/dexterslab-frontend/public/wallpaper.png
desktop_bg=#000000
desktop_fg=#ffffff
desktop_shadow=#000000
desktop_font=sans-serif 12
show_wm_menu=0
sort=mtime;ascending;
show_documents=0
show_trash=0
show_mounts=0

[Observer_Hub.desktop]
x=490
y=250

[Offline_Observer.desktop]
x=490
y=480

[Scan_WIFI.desktop]
x=490
y=710

[Terminal.desktop]
x=250
y=480

[Browser.desktop]
x=730
y=480
